### ISSUE TITLE
Integrate Firebase Messaging Service into COWJ

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#1]
We would like to use COWJ to send notifications to users using COWJ. However, a multicast using Firebase REST API https://firebase.google.com/docs/cloud-messaging/send-message#send-messages-to-multiple-devices requires using sub requests which is not usually exposed as a part of http libraries. Therefore we want to integrate firebase library into COWJ. Specifically the `com.google.firebase.messaging` library

**Comment by nmondal** [comment]
In this case we need to integrate it as data source.
We add the library into the mix in the build.gradle - and we have to expose the important Class instance of firebase as DataSource interface as done in the file:
https://github.com/nmondal/cowj/blob/main/app/src/main/java/cowj/DataSource.java

Specifically add a datasource type "firebase" and add it up in the `UNIVERSAL`.
`G_STORAGE` is a sample data source.
