### ISSUE TITLE
Some of the subsystems, if failed, should abort the runtime - but it does not

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#112]
Bad routing, bad plugin, bad data source, bad auth - all should abort the system.
It does not, and leave the system into a state of semi functioning limbo.

One thing was noted:
In any auth aware project, remove the casbin files.
This raise error, and with that error - filters, and file watchers stop working cause the error happened and those code were not executed.

**Comment by nmondal** [comment]
The right way to fix it is to have a spec on what are acceptable degradation. 
An extreme way to fix it is to simply claim - "No error in init is the right start".

**Comment by nmondal** [comment]
This code can be used to fix any exception which may make the system "hang" while still serving the web server.

```java
// in ModelRunner.run()

initExceptionHandler((e) -> {
            logger.error("Ignition failed!", e);
            System.exit(-5);
        });
```

**Comment by HemilTheRebel** [comment]
@nmondal didnt get that. This is a built in provided by spark?

**Comment by nmondal** [comment]
Yeah this is provided by spark. So try this and we should just test if the stuff just stops the app in limbo :-)

**Comment by hemil-ruparel-blox** [comment]
Sure
