### ISSUE TITLE
Allow data sources to get the base directory so the files can use _/ notation

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#2]
The yaml file allows file paths to be specified using _/ notation. Example -
```
routes:
  get:
    /hello/g: _/hello.groovy
    /hello/j: _/hello.js
    /hello/p: _/hello.py
    /hello/z: _/hello.zm
```

_/hello.groovy means hello.groovy in the directory of the configuration file. This allows the file to be relocated as long as the relative paths are preserved. But we are not exposing the base directory to data sources. Many data sources would need files as input which are best specified as relative paths in order to facilitate relocation

**Comment by nmondal** [comment]
Legit.
This can be fixed by changing the:

```java
DataSource create(String name, Map<String,Object> config);
```
to

```java
DataSource create(String name, Map<String,Object> config, Model parent);
```
And then updating the lambdas. Also we need to accomodate the change in ModelRunner.

**Comment by hemil-ruparel-blox** [comment]
Do we really need access to the model?

**Comment by hemil-ruparel-blox** [comment]
I think it will be much more flexible if we use Map<String, Object> with known values that we pass in

**Comment by nmondal** [comment]
Last commit closes this too.
