### ISSUE TITLE
proxy implementation is not right

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#20]
Currently CURLWrapper makes a half hearted effort into being a forward proxy.
The massaging of  headers and the request body & query params from client to the destination server.

```scala
def send( headers, body, params) {
  // producing payload to destination server 
}
```

But the reverse transform functionality is missing.

```scala
def receive( headers, body, status ) {
  // producing payload to client  
}
```

The proposal for the transform could  be:

```yaml
proxy:
  send: _/send.zm
  receive: _/rec.zm
```

**Comment by nmondal** [comment]
This did not age well. Our understanding of the Spark was poor.
As we found out, we do not need transformers.
Well, we do need transformers, but they can easily be done using `before()` and `after()` filters.

The protocol could be:

`before` sets up the request attribute of `_proxy` with these changes, and then system runs picking up the 
attribute. Using `_shared` also we can create a unique storage.

**Comment by hemil-ruparel-blox** [comment]
@nmondal thats a great idea

**Comment by nmondal** [comment]
This https://github.com/nmondal/cowj/commit/6e56d45dd0d5e0f3126e0f20afd0430f807b540e
Fixes this, once and for all.
