### ISSUE TITLE
Caching - preloading data should be a neat trick

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#22]
Cowj should let preload data.
After a night of thinking I believe we can simply add cron jobs which solves the problem for most - in entirety.

**Comment by hemil-ruparel-blox** [comment]
Where will cron jobs dump the data?

**Comment by nmondal** [comment]
@hemil-ruparel-blox cron dumps it to... `_shared` or anywhere it wishes to.
Including redis.
