### ISSUE TITLE
JDBC Wrapper should have connection pooling

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#28]
https://www.baeldung.com/java-connection-pooling
https://www.baeldung.com/hikaricp

I mean we can work w/o it, but .. it is better to have it.

@hemil-ruparel-blox

**Comment by hemil-ruparel-blox** [comment]
Yup. I will work on this today

**Comment by nmondal** [comment]
@hemil-ruparel-blox  no need to be that urgent.. it is ok... take your time.

**Comment by nmondal** [comment]
After a lot of thinking, what we really need is not pooling, but refresh connection.

**Comment by nmondal** [comment]
We do have a just in time per thread connection. The trouble is, if the thread dies, the connection possibly do not die with it. This can be mitigated by 2 ways.
@hemil-ruparel-blox  came up with a fine idea - hack the JVM itself:
https://github.com/nmondal/cowj/blob/autoclose-connection/app/src/main/java/cowj/plugins/JDBCWrapper.java
Which is very pure, to the point of being self evident.
Sans the non trivial amount of open one has to do with JVM 9+.
This makes it very radical, but correct and precise.

Other option is mundane, GC based solution.
We keep the connections in our own  concurrent  Map<Thread,Connection>.

We keep a cron special job which wakes up say - every 5 mins.
Finds any thread - which is dead .. and we simply close the connection and collect it.
Mundane, but reasonably effective.

**Comment by hemil-ruparel-blox** [comment]
I will try today to see if the hack works. If it does, we are golden. Problem is right now, hack makes our server 5 times slower I don't know why. Need to figure it out.

I didn't understand the third option. Does it mean implement your own thread pool?

**Comment by nmondal** [comment]
Discussion about Jetty arch.
https://stackoverflow.com/questions/62826590/how-does-jetty-handle-threads-and-threadpools-it-uses-too-much-memory

**Comment by nmondal** [comment]
This seems to do exactly what we wanted to achieve.
https://github.com/jhalterman/expiringmap

**Comment by nmondal** [comment]
Waiting for folks to properly verify this.

**Comment by hemil-ruparel-blox** [comment]
Tested. Works. Connection closed as expected
