### ISSUE TITLE
JavaScript - Nashorn - print() does not work

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#35]
Seems to be a problem in Nashorn. Solution is easy, just extending TestAsserter for the same.

Test.print() is System.out.printf()
Test.printe() is System.err.printf()

**Comment by hadric** [comment]
tried it Test.print()
but getting 
TypeError: Cannot find function print in object cowj.Scriptable$$Lambda$287/0x00000008013aeb90@59a6b32f. (eval[#64](https://www.linkedin.com/feed/hashtag/?keywords=%2364)) in
eval at line number 64 at column number 0

**Comment by nmondal** [comment]
@hadric  you have to take the latest pull.
I have tested it, they all run.
We shall deploy the stuff tomorrow in the snapshot repo.

**Comment by hadric** [comment]
it is working now. We can close the ticket.
