### ISSUE TITLE
Better way of writing input validations

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#5]
For input validations, there are lots of cases of:

```
if (foo) {
    return jstr({'error: 'description'})
}
```

Figure out a better way for input validations

**Comment by nmondal** [comment]
Legitimate.
We have added the ZoomBA assertions into the mix.
For JSR we shall also add them as higher functions.
If one can see the route of :

```yaml
get:
   /error: _/error.zm 
```
In there we are simply doing:

```scala
panic(true, "boom!", 418 )
```
As per the latest commit. This should do it.

**Comment by hemil-ruparel-blox** [comment]
b62699a7 Fixes this
