### ISSUE TITLE
JDBC Data source timing related load failure 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#55]
Imagine the JDBC db server is booting up  -  while the cowj is booting up.
Now, cowj knowingly throws an error at boot - because it fails to connect to the db in the load time in the Cowj running thread.

Given the "architecture" is about getting dedicated Connection per thread based on lazy loading, 
this  at best should be configurable.

**Comment by nmondal** [comment]
`no-crash-boot` is a new config property that we can now use in JDBCWrapper to ensure things gets booted even if connection failure happens.
It is suggested to use it rarely in prod.

**Comment by hemil-ruparel-blox** [comment]
Works
