### ISSUE TITLE
Unchecked exceptions returned as response instead of generic error message

### ISSUE THREAD

**Issue by hemil-ruparel-blox** [nmondal/cowj#56]
A route with the following code:

`1 / 0`

Returns response as:
```
java.lang.RuntimeException: zoomba.lang.core.types.ZException$ArithmeticLogicOperation: Invalid Arithmetic Logical Operation [/] :  --> /Users/hemil/blox/cowj_apis/api/location.zm:1:5 to 5 --> ( Can not do operation ( DIVISION ) :
 ( 1 ) with ( 0 ) !
 left: java.lang.Integer 
 right: java.lang.Integer )
 ```
 
Instead of a generic internal server error

**Comment by nmondal** [comment]
In non prod mode we should show these, and in prod mode we should just silence it out so it does not gets thrown to the end user.

**Comment by nmondal** [comment]
We should update in the manual more about the non-prod mode, where random errors will be propagated to the users, as well as automatic load of scripts will happen.
