### ISSUE TITLE
Async not working for proxies end points

### ISSUE THREAD

**Issue by sachblox** [nmondal/cowj#57]
Async functionality is currently not handled for proxies end points

**Comment by nmondal** [comment]
This has very useful value add to be honest.
We can proxy thousands of requests to an external notification handler - if we can just have this facilty.
The code would be a little bit involved.

**Comment by hemil-ruparel-blox** [comment]
@nmondal this is worked as expected. Both error and success cases are working

**Comment by nmondal** [comment]
Awesome, hence closing this.
