### ISSUE TITLE
We should support JWT based auth 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#66]
This should not be a big problem.
https://www.baeldung.com/java-jwt-token-decode

**Comment by nmondal** [comment]
From here:
https://stackoverflow.com/questions/23808460/jwt-json-web-token-library-for-java
https://github.com/jwtk/jjwt
should be a good inclusion.

**Comment by nmondal** [comment]
Or may be no need to pollute with a library.
https://github.com/metamug/java-jwt/blob/master/src/main/java/com/metamug/jwt/JWebToken.java

**Comment by nmondal** [comment]
This is now supported.
Take a look around this file:
https://github.com/nmondal/cowj/blob/main/app/src/test/java/cowj/plugins/JWTAuthenticatorTest.java

**Comment by hemil-ruparel-blox** [comment]
@nmondal this works. Closing the issue

**Comment by hemil-ruparel-blox** [comment]
A good to have would be RSA support so we can keep expose public key :P
