### ISSUE TITLE
JDBCWrapper does not write back   - need update() support 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#69]

**Comment by nmondal** [comment]
This is now done with this commit, in a proper way.
https://github.com/nmondal/cowj/commit/50d6e9d2c2ad35fc75bfe9901612ae5b6f23630c

**Comment by sachblox** [comment]
This has been working fine now, supports insertion/updation as well.

**Comment by nmondal** [comment]
Cool! Thanks.
Closing this.
