### ISSUE TITLE
TypeSystem should be accessible programmatically

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#70]
In some cases it makes sense to load schema and match against data loaded from various sources.
In those cases it makes sense to have programmatic schema verification.

**Comment by nmondal** [comment]
One can now use typesystem via:

```scala
ts = _ds["ds:types"] 
assert ( ts.match("json-schema-file.json", object) ,  "Object Did not match schema!" )
```

**Comment by hemil-ruparel-blox** [comment]
@nmondal can we close this issue then?

**Comment by sachblox** [comment]
TypeSystem is currently not accessible through cron jobs.

**Comment by nmondal** [comment]
@sachblox  this is done now, here is a reference impl.
https://github.com/nmondal/cowj/blob/main/app/samples/prod/cron.zm

Run with the latest.

**Comment by sachblox** [comment]
@nmondal This is working as expected.
