### ISSUE TITLE
cow-0.1-SNAPSHOT.jar should be corrected as cowj-0.1-SNAPSHOT.jar in the doc

### ISSUE THREAD

**Issue by BenitoJD** [nmondal/cowj#73]
6.Ensure ls returns java -jar cow-0.1-SNAPSHOT.jar as well as a deps/ folder. If those two don’t exist, run gradle clean and gradle build -x test
7.java -jar cow-0.1-SNAPSHOT.jar ../../samples/hello/hello.yaml

The corrected comments below for https://github.com/nmondal/cowj#cowj-setup
  java -jar cowj-0.1-SNAPSHOT.jar  and 
java -jar cowj-0.1-SNAPSHOT.jar ../../samples/hello/hello.yaml

**Comment by nmondal** [comment]
This fixes it.
https://github.com/nmondal/cowj/commit/e46b7887ca34bf809158cf826912cb185b5778a7

Thanks @BenitoJD 
Let us know what else you think is missing.
If this is done, please feel free to close it.

**Comment by BenitoJD** [comment]
All good.
