### ISSUE TITLE
A good feature would be to verify query parameter verification via schema 

### ISSUE THREAD

**Issue by nmondal** [nmondal/cowj#95]
@hemil-ruparel-blox  we talked about it.

**Comment by hemil-ruparel-blox** [comment]
Hmm. I was thinking: Query Parameters are just a `Map<String, List<String> | String>`. We should ideally be able to reuse JSON Schema and just pass in the query parameter map. What do you think?

**Comment by hemil-ruparel-blox** [comment]
Looks good to me
